version: '3.8'
services:
 mongodb:
  image: mongo
  container_name: restapi_mongodb
  ports:
   - "27017:27017"
  volumes:
   - mongodb_data:/data/db



 backend:
  build: ./
  container_name: backend_restapi
  depends_on:
   - mongodb
  ports:
   - "3000:3000"
  environment:
   - MONGODB_URI:"mongodb://mongodb:27017"
   - PORT=3000
  volumes: 
   - ./:/app
   - /app/node_modules



volumes:
 mongodb_data:
